name: face_recognition
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  camera: ^0.9.8+1
  firebase_core: any
  google_mlkit_face_detection: any
  image: ^3.0.2
  cloud_firestore: any
  image_picker: any
  path_provider: ^2.1.5
  google_mlkit_commons: any
  path: any
  tflite_flutter:
  firebase_auth:
  http:
  file_picker:
  excel:
  mailer:
  flutter_dotenv:
  provider:
  intl:
  cloudinary_public: ^0.23.1
  cloudinary_sdk:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/Tajawal-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700