// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpc7Fk_20iduJJsvWOVLFFSQauWOR5LDY',
    appId: '1:300449714333:web:78f7c744afc0604c81c474',
    messagingSenderId: '300449714333',
    projectId: 'face-recognition-75a3f',
    authDomain: 'face-recognition-75a3f.firebaseapp.com',
    storageBucket: 'face-recognition-75a3f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHaMzXZ425SS_IunoYooPLi8gkoLozXpk',
    appId: '1:300449714333:android:1dd61dda71606db381c474',
    messagingSenderId: '300449714333',
    projectId: 'face-recognition-75a3f',
    storageBucket: 'face-recognition-75a3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIyagB6f7Ag01nLXrUVYZQmZJ1ERoryuQ',
    appId: '1:300449714333:ios:a0896b006f99941881c474',
    messagingSenderId: '300449714333',
    projectId: 'face-recognition-75a3f',
    storageBucket: 'face-recognition-75a3f.firebasestorage.app',
    iosBundleId: 'com.example.faceRecognition33',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIyagB6f7Ag01nLXrUVYZQmZJ1ERoryuQ',
    appId: '1:300449714333:ios:f4888675cc00188c81c474',
    messagingSenderId: '300449714333',
    projectId: 'face-recognition-75a3f',
    storageBucket: 'face-recognition-75a3f.firebasestorage.app',
    iosBundleId: 'com.example.faceRecognition',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpc7Fk_20iduJJsvWOVLFFSQauWOR5LDY',
    appId: '1:300449714333:web:dfcd29f9538a578381c474',
    messagingSenderId: '300449714333',
    projectId: 'face-recognition-75a3f',
    authDomain: 'face-recognition-75a3f.firebaseapp.com',
    storageBucket: 'face-recognition-75a3f.firebasestorage.app',
  );
}
